// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	favoriteFieldNames          = builder.RawFieldNames(&Favorite{})
	favoriteRows                = strings.Join(favoriteFieldNames, ",")
	favoriteRowsExpectAutoSet   = strings.Join(stringx.Remove(favoriteFieldNames, "`favorite_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	favoriteRowsWithPlaceHolder = strings.Join(stringx.Remove(favoriteFieldNames, "`favorite_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFavoriteFavoriteIdPrefix    = "cache:favorite:favoriteId:"
	cacheFavoriteUserIdVideoIdPrefix = "cache:favorite:userId:videoId:"
)

type (
	favoriteModel interface {
		Insert(ctx context.Context, data *Favorite) (sql.Result, error)
		FindOne(ctx context.Context, favoriteId int64) (*Favorite, error)
		FindOneByUserIdVideoId(ctx context.Context, userId int64, videoId int64) (*Favorite, error)
		Update(ctx context.Context, data *Favorite) error
		Delete(ctx context.Context, favoriteId int64) error
	}

	defaultFavoriteModel struct {
		sqlc.CachedConn
		table string
	}

	Favorite struct {
		FavoriteId int64  `db:"favorite_id"` // 自增id，优化插入效率
		UserId     int64  `db:"user_id"`     // 用户id
		VideoId    int64  `db:"video_id"`    // 视频id
		Behavior   string `db:"behavior"`    // 1:点赞 2:未点赞
	}
)

func newFavoriteModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFavoriteModel {
	return &defaultFavoriteModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`favorite`",
	}
}

func (m *defaultFavoriteModel) withSession(session sqlx.Session) *defaultFavoriteModel {
	return &defaultFavoriteModel{
		CachedConn: m.CachedConn.WithSession(session),
		table:      "`favorite`",
	}
}

func (m *defaultFavoriteModel) Delete(ctx context.Context, favoriteId int64) error {
	data, err := m.FindOne(ctx, favoriteId)
	if err != nil {
		return err
	}

	favoriteFavoriteIdKey := fmt.Sprintf("%s%v", cacheFavoriteFavoriteIdPrefix, favoriteId)
	favoriteUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheFavoriteUserIdVideoIdPrefix, data.UserId, data.VideoId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `favorite_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, favoriteId)
	}, favoriteFavoriteIdKey, favoriteUserIdVideoIdKey)
	return err
}

func (m *defaultFavoriteModel) FindOne(ctx context.Context, favoriteId int64) (*Favorite, error) {
	favoriteFavoriteIdKey := fmt.Sprintf("%s%v", cacheFavoriteFavoriteIdPrefix, favoriteId)
	var resp Favorite
	err := m.QueryRowCtx(ctx, &resp, favoriteFavoriteIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `favorite_id` = ? limit 1", favoriteRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, favoriteId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFavoriteModel) FindOneByUserIdVideoId(ctx context.Context, userId int64, videoId int64) (*Favorite, error) {
	favoriteUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheFavoriteUserIdVideoIdPrefix, userId, videoId)
	var resp Favorite
	err := m.QueryRowIndexCtx(ctx, &resp, favoriteUserIdVideoIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `video_id` = ? limit 1", favoriteRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, videoId); err != nil {
			return nil, err
		}
		return resp.FavoriteId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFavoriteModel) Insert(ctx context.Context, data *Favorite) (sql.Result, error) {
	favoriteFavoriteIdKey := fmt.Sprintf("%s%v", cacheFavoriteFavoriteIdPrefix, data.FavoriteId)
	favoriteUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheFavoriteUserIdVideoIdPrefix, data.UserId, data.VideoId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, favoriteRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.VideoId, data.Behavior)
	}, favoriteFavoriteIdKey, favoriteUserIdVideoIdKey)
	return ret, err
}

func (m *defaultFavoriteModel) Update(ctx context.Context, newData *Favorite) error {
	data, err := m.FindOne(ctx, newData.FavoriteId)
	if err != nil {
		return err
	}

	favoriteFavoriteIdKey := fmt.Sprintf("%s%v", cacheFavoriteFavoriteIdPrefix, data.FavoriteId)
	favoriteUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheFavoriteUserIdVideoIdPrefix, data.UserId, data.VideoId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `favorite_id` = ?", m.table, favoriteRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.VideoId, newData.Behavior, newData.FavoriteId)
	}, favoriteFavoriteIdKey, favoriteUserIdVideoIdKey)
	return err
}

func (m *defaultFavoriteModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFavoriteFavoriteIdPrefix, primary)
}

func (m *defaultFavoriteModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `favorite_id` = ? limit 1", favoriteRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFavoriteModel) tableName() string {
	return m.table
}
