// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package videoclient

import (
	"context"

	"TikTok/apps/video/rpc/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BasicVideoInfo        = video.BasicVideoInfo
	BasicVideoInfoReq     = video.BasicVideoInfoReq
	BasicVideoInfoResp    = video.BasicVideoInfoResp
	FeedReq               = video.FeedReq
	FeedResp              = video.FeedResp
	PublishActionReq      = video.PublishActionReq
	PublishActionResp     = video.PublishActionResp
	PublishListReq        = video.PublishListReq
	PublishListResp       = video.PublishListResp
	WorkCountByUserIdReq  = video.WorkCountByUserIdReq
	WorkCountByUserIdResp = video.WorkCountByUserIdResp
	NotifyHotVideoReq     = video.NotifyHotVideoReq 
	NotifyHotVideoResp    = video.NotifyHotVideoResp
	CheckHotVideoReq 	  = video.CheckHotVideoReq
	CheckHotVideoResp 	  = video.CheckHotVideoResp
	VideoPusherReq 		  = video.VideoPusherReq
	VideoPusherResp 	  = video.VideoPusherResp
	Video interface {
		GetWorkCountByUserId(ctx context.Context, in *WorkCountByUserIdReq, opts ...grpc.CallOption) (*WorkCountByUserIdResp, error)
		GetFeed(ctx context.Context, in *FeedReq, opts ...grpc.CallOption) (*FeedResp, error)
		SendPublishAction(ctx context.Context, in *PublishActionReq, opts ...grpc.CallOption) (*PublishActionResp, error)
		GetPublishList(ctx context.Context, in *PublishListReq, opts ...grpc.CallOption) (*PublishListResp, error)
		Detail(ctx context.Context, in *BasicVideoInfoReq, opts ...grpc.CallOption) (*BasicVideoInfoResp, error)
		NotifyHotVideo(ctx context.Context, in *NotifyHotVideoReq, opts ...grpc.CallOption) (*NotifyHotVideoResp, error)
		CheckHotVideo(ctx context.Context, in *CheckHotVideoReq, opts ...grpc.CallOption) (*CheckHotVideoResp, error)
		VideoPusher(ctx context.Context, in *VideoPusherReq,opts ...grpc.CallOption) (*VideoPusherResp, error) 
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

func (m *defaultVideo) GetWorkCountByUserId(ctx context.Context, in *WorkCountByUserIdReq, opts ...grpc.CallOption) (*WorkCountByUserIdResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetWorkCountByUserId(ctx, in, opts...)
}

func (m *defaultVideo) GetFeed(ctx context.Context, in *FeedReq, opts ...grpc.CallOption) (*FeedResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetFeed(ctx, in, opts...)
}

func (m *defaultVideo) SendPublishAction(ctx context.Context, in *PublishActionReq, opts ...grpc.CallOption) (*PublishActionResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.SendPublishAction(ctx, in, opts...)
}

func (m *defaultVideo) GetPublishList(ctx context.Context, in *PublishListReq, opts ...grpc.CallOption) (*PublishListResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetPublishList(ctx, in, opts...)
}

func (m *defaultVideo) Detail(ctx context.Context, in *BasicVideoInfoReq, opts ...grpc.CallOption) (*BasicVideoInfoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.Detail(ctx, in, opts...)
}

func (m *defaultVideo) NotifyHotVideo(ctx context.Context, in *NotifyHotVideoReq, opts ...grpc.CallOption) (*NotifyHotVideoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.NotifyHotVideo(ctx, in, opts...)
}

func (m *defaultVideo) CheckHotVideo(ctx context.Context, in *CheckHotVideoReq,opts ...grpc.CallOption) (*CheckHotVideoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.CheckHotVideo(ctx, in, opts...)
}

func (m *defaultVideo) VideoPusher(ctx context.Context, in *VideoPusherReq,opts ...grpc.CallOption) (*VideoPusherResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.VideoPusher(ctx, in, opts...)
}