// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"TikTok/apps/user/rpc/internal/logic"
	"TikTok/apps/user/rpc/internal/svc"
	"TikTok/apps/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterReq) (*user.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Detail(ctx context.Context, in *user.BasicUserInfoReq) (*user.BasicUserInfoResp, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}

func (s *UserServer) SetAvatar(ctx context.Context, in *user.SetAvatarReq) (*user.SetAvatarResp, error) {
	l := logic.NewSetAvatarLogic(ctx, s.svcCtx)
	return l.SetAvatar(in)
}

func (s *UserServer) SetBackgroundImage(ctx context.Context, in *user.SetBackgroundImageReq) (*user.SetBackgroundImageResp, error) {
	l := logic.NewSetBackgroundImageLogic(ctx, s.svcCtx)
	return l.SetBackgroundImage(in)
}

func (s *UserServer) SetSignature(ctx context.Context, in *user.SetSignatureReq) (*user.SetSignatureResp, error) {
	l := logic.NewSetSignatureLogic(ctx, s.svcCtx)
	return l.SetSignature(in)
}
